# Generated by Django 5.0.6 on 2024-07-13 23:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
