# Generated by Django 5.0.6 on 2024-07-21 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_post_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
