# Generated by Django 5.0.7 on 2024-08-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
