# Generated by Django 5.0.6 on 2024-07-26 17:42
from django.db import migrations

def set_default_slug(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.filter(slug__isnull=True):
        profile.slug = 'default-slug'  # Or generate a unique slug
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_slug'),
    ]

    operations = [
        migrations.RunPython(set_default_slug),
    ]
