# Generated by Django 5.0.6 on 2024-08-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_contactquery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="folder",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="folder",
            field=models.ManyToManyField(
                blank=True, related_name="portfolio_images", to="users.folder"
            ),
        ),
    ]
