# Generated by Django 5.0.6 on 2024-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_portfolio_folder_portfolio_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
