# Generated by Django 5.0.6 on 2024-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0002_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=75),
        ),
    ]
