# Generated by Django 5.0.6 on 2024-05-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0003_alter_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitness",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="service",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
