# Generated by Django 5.0.6 on 2024-07-16 23:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0008_course_banner_lesson_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="fitness",
            name="name",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=75),
        ),
    ]
