# Generated by Django 5.0.6 on 2024-07-18 14:47

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0009_alter_course_body_alter_fitness_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75)),
                ("body", tinymce.models.HTMLField()),
            ],
        ),
    ]
