# Generated by Django 5.0.6 on 2025-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_herophrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='herophrase',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ha', 'Hausa'), ('yo', 'yoruba'), ('ig', 'Igbo'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
