# Generated by Django 5.0.6 on 2025-07-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_affiliatetool_leadmagnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('logo', models.ImageField(blank=True, upload_to='tools/')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
